// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaI_jy8t5fryFml8eG49_g6agkIpbpW8g',
    appId: '1:866709152606:web:5672fe0f2bd718250d65cf',
    messagingSenderId: '866709152606',
    projectId: 'myportfolio-84e1e',
    authDomain: 'myportfolio-84e1e.firebaseapp.com',
    storageBucket: 'myportfolio-84e1e.appspot.com',
    measurementId: 'G-MQGKN2F1B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdppLjPXqgrNcLgTTtvEsdV5-0qkS0SQY',
    appId: '1:866709152606:android:1fcf90354eda7bff0d65cf',
    messagingSenderId: '866709152606',
    projectId: 'myportfolio-84e1e',
    storageBucket: 'myportfolio-84e1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTGVY4OxS0YIsHRFLN0Y7J1xaOdIfHFiw',
    appId: '1:866709152606:ios:680ab57db3a2788f0d65cf',
    messagingSenderId: '866709152606',
    projectId: 'myportfolio-84e1e',
    storageBucket: 'myportfolio-84e1e.appspot.com',
    iosClientId: '866709152606-7l5osdbl5it9v60todr9hsgsr0ni9s12.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfoliio2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTGVY4OxS0YIsHRFLN0Y7J1xaOdIfHFiw',
    appId: '1:866709152606:ios:5be6affa7033ca910d65cf',
    messagingSenderId: '866709152606',
    projectId: 'myportfolio-84e1e',
    storageBucket: 'myportfolio-84e1e.appspot.com',
    iosClientId: '866709152606-k10fg4d8s4epsa14kcss22rbo632u38q.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfoliio2.RunnerTests',
  );
}
